FROM amazonlinux:2023

WORKDIR /var/task

RUN dnf install -y \
        python3 \
        python3-pip \
        python3-devel \
        gcc \
        gcc-c++ \
        libjpeg-turbo-devel \
        zlib-devel \
        freetype-devel \
        lcms2-devel \
        tcl-devel \
        tk-devel \
        zip \
    && dnf clean all

RUN mkdir -p /var/task/python

RUN pip3 install --target /var/task/python pillow

WORKDIR /var/task/python
RUN zip -r9 ../pillow-layer.zip .

CMD [ "bash" ]